kind: AIchorManifest
apiVersion: 0.2.2

builder:
  image: image
  dockerfile: ./Dockerfile
  context: .  
  buildArgs: 
    JFROG_BASE_REPOSITORY: aichor-dev-docker
    JFROG_URL: artifactory.bion.tech 

spec:
  operator: ray 
  image: image
  command: "python3 -u main.py --operator=ray --sleep=300 --tb-write=True"

  tensorboard:
    enabled: true

  types: 
    Head:
      resources:
        cpus: 1
        ramRatio: 2 
        accelerators: # optional
          gpu:
            count: 0
            product: a10g
            type: gpu

    Job:
      resources:
        cpus: 1
        ramRatio: 2
        shmSizeGB: 0

    Workers:
      - name: cpu-workers
        count: 128
        resources:
          cpus: 1
          ramRatio: 2
          shmSizeGB: 0
